#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/bootstrap
uci commit luci

uci set system.@system[0].hostname=LEDE
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set network.lan.ipaddr="192.168.168.1"
uci set network.lan.ifname="eth0"
uci set network.wan.ifname="eth1"
uci commit network

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/cupsd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/nfs.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/cifs.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/qbittorrent.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

sed -i 's/\"network\"/\"services\"/g' /usr/lib/lua/luci/controller/dnspod.lua
#sed -i 's/\"services\"/\"QOS\"/g' /usr/lib/lua/luci/controller/qosv4.lua
sed -i 's/\"network\"/\"control\"/g' /usr/lib/lua/luci/controller/eqos.lua
#sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/qos.lua
#sed -i 's/\"network\"/\"QOS\"/g' /usr/lib/lua/luci/controller/sqm.lua
#sed -i 's/\"services\"/\"QOS\"/g' /usr/lib/lua/luci/controller/nft-qos.lua
sed -i 's/\"services\"/\"vpn\"/g' /usr/lib/lua/luci/controller/softethervpn5.lua
sed -i 's/\"network\"/\"control\"/g' /usr/lib/lua/luci/controller/appfilter.lua

ln -sf /sbin/ip /usr/bin/ip

sed -i 's#http://downloads.openwrt.org#https://mirrors.ustc.edu.cn/lede#g' /etc/opkg/distfeeds.conf
sed -i 's#src/gz openwrt_luci https://mirrors.ustc.edu.cn/lede/snapshots#src/gz openwrt_luci https://mirrors.ustc.edu.cn/lede/releases/18.06.8#g' /etc/opkg/distfeeds.conf
sed -i 's#src/gz openwrt_packages https://mirrors.ustc.edu.cn/lede/snapshots#src/gz openwrt_packages https://mirrors.ustc.edu.cn/lede/releases/18.06.8#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
#sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i "s/# //g" /etc/opkg/distfeeds.conf

uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci commit dhcp

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='E20.6.8 From CTCGFW'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

sed -i 's/LuCI Master/LuCI 18.06-branch/g' /usr/lib/lua/luci/version.lua
#sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
#echo 'luciversion = "Mod20.04 by CTCGFW"' >> /usr/lib/lua/luci/version.lua

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua
echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

#禁用ipv6.
#echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
#echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
#echo net.ipv6.conf.lo.disable_ipv6 = 1 >> /etc/sysctl.conf
#echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
exit 0
